### PR TITLE
Zygote -> Chainrules (3)

### PR DESCRIPTION
**Pull request by MasonProtter**
Forking the repo over to JuliaFolds2 and removing the `Run.jl` test infrastructure in favour of vanilla Test.jl

Superscedes https://github.com/JuliaFolds/BangBang.jl/pull/237

### CODE REVIEW

**Comment by MasonProtter** [comment]
Okay, the test suite is now passing! 

I don't know anything about depoloying or migrating the documentation to this repo though. Could anyone advise on how we can do that? If it'll take significant work, I can just merge this PR and then we can start a new one to figure out docs.

**Comment by fredrikekre** [comment]
Should be sufficient to use `DocumenterTools.genkeys` and upload the key pair, and possibly update gh pages setting in the repo settings.

**Comment by lmiq** [comment]
I can do that. I just did the same in another repo, let me know if you want me to do it.

**Comment by MasonProtter** [comment]
Yes that would be great if you could do it @lmiq!

I’ll go ahead abd merge this PR then.

**Pull request merged**
